### PR TITLE
SCTP support

### PR DESCRIPTION
**Pull request by ishidawataru**

### CODE REVIEW

**Comment by ishidawataru** [comment]
@AkihiroSuda thanks for your review. Reflected your comments. PTAL

**Comment by AkihiroSuda** [comment]
LGTM when it become compilable on non-linux/amd64

**Comment by ishidawataru** [comment]
@AkihiroSuda  done. PTAL

**Comment by AkihiroSuda** [comment]
LGTM.

I'll try to send PR to ishidawataru/sctp for supporting other platforms, and look into how to add "ErrUnsupported" for swarm things.

**Pull request closed without merging**
